### PR TITLE
Fix SocketDebugger

### PR DESCRIPTION
**Pull request by konukhov**
Hi,

I guess nobody has used SocketDebugger before, because the class was completely broken and nobody has noticed that. Anyway, I needed it for some debugging, so I fixed it.

I didn't write specs for the class itself because it just mostly delegates its methods to TCPSocket, but I rewrote connection_spec.rb to be sure that connection will work with a custom socket class.

I hope for someone it will be useful.

### CODE REVIEW

**Comment by jferris** [comment]
>  Anyway, I needed it for some debugging, so I fixed it.

Thanks! I'm curious: what did you need it for?

This was never really intentionally exposed to users. I largely used it when I was authoring the wire protocol between the Ruby and C++ implementations and needed to figure out what was going back and forth. I was planning to remove it (see #757). The fact that it's totally broken confirms my suspicion that nobody is using it.

@mhoran any thoughts here? I'm leaning towards removing it immediately, as it's broken and was never really part of the public API. Think we can remove without deprecating?

**Comment by konukhov** [comment]
@jferris We couldn't get capybara-webkit working in our CI environment on Ubuntu 14.04 – all tests involving webkit were failing with Broken Pipe error on any version of Qt. So I dug into capybara-webkit code and found this class which I then used for debugging. We ended up recompiling Qt with some configuration options, it helped.

Actually, I'm not sure if SocketDebugger really helped me to solve this issue, but I thought that maybe someone could find it and it would somehow help to figure out something.

**Comment by konukhov** [comment]
@jferris Anyway, I didn't saw the issue you mentioned. I wouldn't have sent this PR if I did.

**Comment by mhoran** [comment]
@jferris let's go ahead and remove it. Thanks for bringing this to our attention, @konukhov!

**Comment by jferris** [comment]
Addressed in #772.

**Pull request closed without merging**
