### PR TITLE
Link to thoughtbot's contributor code of conduct

### PR DESCRIPTION
**Pull request by mike-burns**

### CODE REVIEW

**Comment by gabebw** [comment]
CI is broken, but I strongly doubt it's due to this.

**Comment by jferris** [comment]
The "by participating in this project, you agree" part makes it sound sort of like a EULA. What about something like:

> We expect users to follow our code of conduct while submitting code or comments.

**Comment by gabebw** [comment]
I like that version, Joe.

**Comment by jferris** [comment]
Merged as b5a8fca.

**Pull request closed without merging**
