### PR TITLE
Possibility to restart webkit server

### PR DESCRIPTION
**Pull request by simonoff**

### CODE REVIEW

**Comment by jarthod** [comment]
Sorry for that but I'll have to reopen this ☺

We have a 14k tests suite with about 1k integration tests, using `capybara-webkit` and selenium. And when run on our CI the `webkit-server` process takes up to 5GB of memory (growing pretty much linearly with test count) whereas doing the same thing with Firefox (selenium) never go over 300MB.

This is, as you can guess, problematic for parallel test execution, even on a big machine.

I tried updating `capybara-webkit` (now using `1.9.0`) and Qt (now using `5.2.1`) but it didn't change anything. So I guess there are memory leaks of course but although I'm comfortable with C/C++/Valgrind I'm not sure how to help here. Do you have any way to extract information from my runs in a way that could be actionable to you ?

In the meanwhile I'll try hacking around to get the `webkit-server` to restart during the test run as it's the only way I have to save my CI.

**Comment by jferris** [comment]
@jarthod I just opened #898 to provide better separation of concerns for booting/connecting to the server. You can use that branch to pass your own server that's already running via Valgrind:

<pre>
% valgrind /path/to/capybara-webkit/bin/webkit_server
==4882== Memcheck, a memory error detector
==4882== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==4882== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==4882== Command: src/webkit_server
==4882== 
Capybara-webkit server started, listening on port: <b>43065</b>
</pre>

``` ruby
class RunningServer
  attr_reader :port

  def initialize(port)
    @port = port
  end

  def start
  end
end

require "capybara/webkit"

Capybara.register_driver :running_webkit do |app|
  webkit_server = RunningServer.new(43065)
  webkit_connection = Capybara::Webkit::Connection.new(server: webkit_server)
  webkit_browser = Capybara::Webkit::Browser.new(webkit_connection)

  Capybara::Webkit::Driver.new(app, browser: webkit_browser)
end

Capybara.driver = :running_webkit
```

You can then boot your server process with valgrind, gbd, or anything else that helps you find leaks.

If you get any interesting heap output from Valgrind, feel free to include it here.

**Comment by jarthod** [comment]
Ok great, I'll have a look at this. For the record and for other people looking at this thread, here is what I managed to hack in order to restart the webkit server every 20 specs (to minimize bootup time impact):
```ruby
RSpec.configure do |config|

  # ...

  $webkit_server_age = 0
  config.after :each, type: :feature do |example|
    if [:selenium, :webkit].include?(Capybara.current_driver)
      Capybara.reset!
    end
    if Capybara.current_driver == :webkit
      # Restart webkit_server every 10 spec to reduce memory leak
      if $webkit_server_age > 20
        driver = Capybara.current_session.driver
        conn = driver.instance_variable_get('@browser').instance_variable_get('@connection')
        Process.kill("TERM", conn.send(:discover_pid))
        conn.restart
        driver.reset!
        $webkit_server_age = 0
      else
        $webkit_server_age += 1
      end
    end
  end
```
This significantly limited the memory leak, the `webkit_server` never goes above 500MB now. Of course it's a crappy solution but it's the only one I found and even though I would love to help reducing these memory leaks I know it's gonna be hard and we'll never eliminate them all.

**Comment by jferris** [comment]
@jarthod The `Connection` class has [`pid` method](https://github.com/thoughtbot/capybara-webkit/blob/e0172bfcd98c29a7d1bdf96282cedeff8fab1fd2/lib/capybara/webkit/connection.rb#L11) that returns the PID, which would let you remove one private method call.

**Comment by jarthod** [comment]
Good point, thanks.

**Comment by jarthod** [comment]
Ok after a first round of investigation, I found that the memory leak is only present on some of our specs,  loading a specific page. I tried removing the JS code specific to this page and the leak seems to be gone so it's at least liked to what this JS do. Unfortunately there's a log of JS here so I'm digging and will keep you posted.

For the record here is what I used to track down which specs caused leaks:

```ruby
def RSS pid
  `ps -o rss -p #{pid}`.strip.split.last.to_i / 1024
end

RSpec.configure do |config|

  # ...

  $webkit_rss = 0
  config.after :each, type: :feature do |example|
    if Capybara.current_driver == :webkit
      driver = Capybara.current_session.driver
      conn = driver.instance_variable_get('@browser').instance_variable_get('@connection')
      mem = RSS(conn.pid)
      puts "webkit_server mem = %4d MB (was %4d MB, %+3d MB)" % [mem, $webkit_rss, (mem - $webkit_rss)]
      $webkit_rss = mem
    end
  end
end
```

**Comment by jarthod** [comment]
Aha I think I found the culprit, still not sure why it leaks yet. It seems to come from this line:
```javascript
var favico = new Favico({animation: 'none'});
```
We're using [favico.js](https://github.com/ejci/favico.js/blob/master/favico.js) to add badges to the page favicon in realtime. And it seems that each time we instantiate this, the `webkit_server` memory increase between 5 and 20MB, and these are never freed. Instantiating / updating multiple time in the same page doesn't seem to increase memory more.

So here are some of my ideas:
- Is there something like a favicon cache ? Is there any way to purge it ?
- Maybe it's the canvas element creation which leaks ?

Any thoughts?

---
Here is a log of 20 tests just doing `visit '/path'` with favico.js:
```
webkit_server mem =  123 MB (was    0 MB, +123 MB)
webkit_server mem =  128 MB (was  123 MB,  +5 MB)
webkit_server mem =  136 MB (was  128 MB,  +8 MB)
webkit_server mem =  153 MB (was  136 MB, +17 MB)
webkit_server mem =  161 MB (was  153 MB,  +8 MB)
webkit_server mem =  172 MB (was  161 MB, +11 MB)
webkit_server mem =  179 MB (was  172 MB,  +7 MB)
webkit_server mem =  190 MB (was  179 MB, +11 MB)
webkit_server mem =  197 MB (was  190 MB,  +7 MB)
webkit_server mem =  208 MB (was  197 MB, +11 MB)
webkit_server mem =  220 MB (was  208 MB, +12 MB)
webkit_server mem =  228 MB (was  220 MB,  +8 MB)
webkit_server mem =  235 MB (was  228 MB,  +7 MB)
webkit_server mem =  250 MB (was  235 MB, +15 MB)
webkit_server mem =  263 MB (was  250 MB, +13 MB)
webkit_server mem =  271 MB (was  263 MB,  +8 MB)
webkit_server mem =  275 MB (was  271 MB,  +4 MB)
webkit_server mem =  287 MB (was  275 MB, +12 MB)
webkit_server mem =  299 MB (was  287 MB, +12 MB)
webkit_server mem =  318 MB (was  299 MB, +19 MB)
```
And here is the same log *without* favico.js
```
webkit_server mem =  123 MB (was    0 MB, +123 MB)
webkit_server mem =  134 MB (was  123 MB, +11 MB)
webkit_server mem =  141 MB (was  134 MB,  +7 MB)
webkit_server mem =  146 MB (was  141 MB,  +5 MB)
webkit_server mem =  146 MB (was  146 MB,  +0 MB)
webkit_server mem =  146 MB (was  146 MB,  +0 MB)
webkit_server mem =  147 MB (was  146 MB,  +1 MB)
webkit_server mem =  157 MB (was  147 MB, +10 MB)
webkit_server mem =  162 MB (was  157 MB,  +5 MB)
webkit_server mem =  163 MB (was  162 MB,  +1 MB)
webkit_server mem =  161 MB (was  163 MB,  -2 MB)
webkit_server mem =  161 MB (was  161 MB,  +0 MB)
webkit_server mem =  161 MB (was  161 MB,  +0 MB)
webkit_server mem =  161 MB (was  161 MB,  +0 MB)
webkit_server mem =  162 MB (was  161 MB,  +1 MB)
webkit_server mem =  163 MB (was  162 MB,  +1 MB)
webkit_server mem =  161 MB (was  163 MB,  -2 MB)
webkit_server mem =  158 MB (was  161 MB,  -3 MB)
webkit_server mem =  157 MB (was  158 MB,  -1 MB)
webkit_server mem =  158 MB (was  157 MB,  +1 MB)
```

**Comment by twalpole** [comment]
@jarthod There's an open issue on the favico.js project about a memory leak - might be what you're seeing: https://github.com/ejci/favico.js/issues/90

**Comment by jarthod** [comment]
It's probably the cause, yes, but in this case shouldn't the page change + Capybara.reset! trash this lost memory ? like closing + opening a new tab ? Because if js leaks bloat the memory after the page is closed that's bad.

**Comment by mhoran** [comment]
It depends on where the leak is. We don't completely tear down the `webkit_server` on `reset!`, so it's likely that there's some memory sticking around outside of the `QWebPage` object that is recreated. If this is a known issue for other WebKit based browsers, it's likely there's an issue deep down in WebKit/WebCore that is not cleaned up without a restart of the server.

**Comment by jarthod** [comment]
Ok thanks :/ I'm gonna help fixing this leak then, and pray for all our js and libs not to leak like that again ☺

**Pull request closed without merging**
